export const imageKeywords = [
    "generate image",
    "create image",
    "make image",
    "generate picture",
    "create picture",
    "make picture",
    "generate photo",
    "create photo",
    "make photo",
    "create art",
    "make art",
    "generate art",
    "draw a ",
    "draw an ",
    "paint a ",
    "paint an ",
    "sketch a ",
    "sketch an ",
];
