import jsPDF from "jspdf";

interface WorksheetData {
  title: string;
  summary: string;
  flashcards: Array<{ front: string; back: string }>;
  quizzes: Array<{
    question: string;
    options?: string[];
    correctAnswer: string;
    explanation?: string;
    type: string;
  }>;
  metadata: {
    region?: string;
    curriculum?: string;
  };
}

export const generateWorksheetPDF = (data: WorksheetData) => {
  const doc = new jsPDF();
  const margin = 20;
  let cursorY = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;

  // Deepshi Theme Colors
  const primaryColor = [6, 182, 212];
  const textColor = [20, 20, 40];
  const accentColor = [37, 99, 235];

  // Helper: Draw line
  const drawDivider = (y: number) => {
    doc.setDrawColor(230, 230, 240);
    doc.line(margin, y, pageWidth - margin, y);
    return y + 10;
  };

  // Helper: Wrapped text with cursor management
  const addText = (text: string, fontSize = 12, fontStyle = "normal", color = textColor) => {
    doc.setFont("helvetica", fontStyle);
    doc.setFontSize(fontSize);
    doc.setTextColor(color[0], color[1], color[2]);
    
    const lines = doc.splitTextToSize(text, contentWidth);
    const textHeight = lines.length * (fontSize * 0.5);
    
    if (cursorY + textHeight > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      cursorY = 20;
    }
    
    doc.text(lines, margin, cursorY);
    cursorY += textHeight + 5;
  };

  // --- Header ---
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, pageWidth, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("Cryonex Study Guide", margin, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`${data.title} | Active Recall Worksheet`, margin, 32);

  cursorY = 55;

  // --- Overview ---
  addText("Study Summary", 16, "bold", primaryColor);
  addText(data.summary, 10, "normal");
  cursorY = drawDivider(cursorY + 5);

  // --- Active Recall Section ---
  if (data.flashcards.length > 0) {
    addText("Active Recall: Key Terms", 16, "bold", primaryColor);
    addText("Try to define these terms without looking at your notes first.", 9, "italic", [100, 100, 120]);
    cursorY += 5;

    data.flashcards.slice(0, 10).forEach((card, index) => {
      addText(`${index + 1}. ${card.front}`, 11, "bold");
      // Add a dotted line for writing space
      doc.setDrawColor(200, 200, 200);
      doc.setLineDashPattern([1, 1], 0);
      doc.line(margin, cursorY, pageWidth - margin, cursorY);
      doc.setLineDashPattern([], 0);
      cursorY += 12;
    });
    cursorY = drawDivider(cursorY + 5);
  }

  // --- Assessment Section ---
  if (data.quizzes.length > 0) {
    addText("Knowledge Check", 16, "bold", primaryColor);
    cursorY += 5;

    data.quizzes.forEach((quiz, index) => {
      addText(`${index + 1}. ${quiz.question}`, 11, "bold");
      
      if (quiz.options) {
        quiz.options.forEach((opt, optIdx) => {
          const prefix = String.fromCharCode(65 + optIdx);
          addText(`   [ ] ${prefix}. ${opt}`, 10, "normal");
        });
      } else {
        // Space for essay/short answer
        cursorY += 5;
        doc.setDrawColor(230, 230, 240);
        doc.rect(margin, cursorY, contentWidth, 30);
        cursorY += 35;
      }
      cursorY += 5;
    });
  }

  // --- Footer ---
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Cryonex AI • Worksheet for ${data.title} • Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // --- Answer Key (Final Page) ---
  doc.addPage();
  cursorY = 20;
  addText("Answer Key", 18, "bold", accentColor);
  cursorY += 10;

  if (data.flashcards.length > 0) {
    addText("Terms & Definitions", 12, "bold", primaryColor);
    data.flashcards.slice(0, 10).forEach((card) => {
      addText(`${card.front}: ${card.back}`, 9, "normal");
    });
    cursorY += 5;
  }

  if (data.quizzes.length > 0) {
    addText("Quiz Answers", 12, "bold", primaryColor);
    data.quizzes.forEach((quiz, index) => {
      addText(`Q${index + 1}: ${quiz.correctAnswer}`, 9, "normal");
      if (quiz.explanation) {
        addText(`Why: ${quiz.explanation}`, 8, "italic", [100, 100, 100]);
      }
    });
  }

  doc.save(`${data.title.replace(/\s+/g, "_")}_Worksheet.pdf`);
};
