import { v } from "convex/values";
import { internalMutation, mutation } from "./_generated/server";
import { getAuthUserId } from "@convex-dev/auth/server";

export const storeDocument = internalMutation({
  args: {
    userId: v.id("users"),
    docId: v.string(),
    meta: v.object({
      title: v.string(),
      pages: v.number(),
      tags: v.optional(v.array(v.string())),
      createdAt: v.string(),
    }),
    extracted: v.object({
      text: v.string(),
      sections: v.array(
        v.object({
          id: v.string(),
          title: v.string(),
          text: v.string(),
        }),
      ),
      tables: v.optional(
        v.array(
          v.object({
            id: v.string(),
            csv: v.string(),
          }),
        ),
      ),
      figures: v.optional(
        v.array(
          v.object({
            id: v.string(),
            caption: v.string(),
            src: v.string(),
          }),
        ),
      ),
    }),
    summary: v.object({
      short: v.string(),
      detailed: v.string(),
      simple: v.optional(v.string()),
    }),
    storageId: v.optional(v.id("_storage")),
    isSTEM: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("studyDocuments", args);
  },
});

export const storeChunk = internalMutation({
  args: {
    docId: v.string(),
    chunkId: v.string(),
    text: v.string(),
    embedding: v.array(v.float64()),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("studyChunks", args);
  },
});

export const saveOrUpdateNote: any = mutation({
  args: {
    docId: v.string(),
    content: v.string(),
    title: v.string(),
  },
  handler: async (ctx, args) => {
    // Use getAuthUserId for consistent auth handling
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Authentication required");

    // Upsert note by docId
    const existingNote = await ctx.db
      .query("studyNotes")
      .withIndex("by_docId", (q) => q.eq("docId", args.docId))
      .first();

    if (existingNote) {
      if (existingNote.userId !== userId) {
        throw new Error("Unauthorized");
      }
      return await ctx.db.patch(existingNote._id, {
        content: args.content,
        title: args.title,
      });
    }

    return await ctx.db.insert("studyNotes", {
      userId,
      docId: args.docId,
      title: args.title,
      content: args.content,
      format: "markdown",
    });
  },
});

export const setMaterialDocId = mutation({
  args: { materialId: v.id("studyMaterials"), docId: v.string() },
  handler: async (ctx, { materialId, docId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Authentication required");

    const material = await ctx.db.get(materialId);
    if (!material || material.userId !== userId) {
      throw new Error("Not found or unauthorized");
    }

    await ctx.db.patch(materialId, { docId });
  },
});

// Mutation to update document summary in studyDocuments table
export const updateDocumentSummary = mutation({
  args: {
    docId: v.string(),
    summary: v.object({
      short: v.string(),
      detailed: v.string(),
      simple: v.optional(v.string()),
    }),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Authentication required");

    const document = await ctx.db
      .query("studyDocuments")
      .withIndex("by_docId", (q) => q.eq("docId", args.docId))
      .first();

    if (document) {
      if (document.userId !== userId) {
        throw new Error("Not found or unauthorized");
      }
      await ctx.db.patch(document._id, {
        summary: args.summary,
      });
      return;
    }

    // Fallback: allow updating summary on studyMaterials-backed docs.
    const materialId = ctx.db.normalizeId("studyMaterials", args.docId);
    if (materialId) {
      const material = await ctx.db.get(materialId);
      if (material && material.userId === userId) {
        await ctx.db.patch(materialId, {
          summary: args.summary,
        });
      }
    }
  },
});

export const createMindMapInternal = internalMutation({
  args: {
    userId: v.id("users"),
    title: v.string(),
    materialId: v.optional(v.id("studyMaterials")),
    nodes: v.array(v.any()),
    edges: v.array(v.any()),
    layout: v.string(),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("mindMaps", {
      userId: args.userId,
      title: args.title,
      materialId: args.materialId,
      nodes: args.nodes,
      edges: args.edges,
      layout: args.layout,
      metadata: {
        createdAt: Date.now(),
        isAutoGenerated: true,
      },
    });
  },
});

export const generateUploadUrl = mutation(async (ctx) => {
  return await ctx.storage.generateUploadUrl();
});
