import { useEffect, useState } from "react";
import { SplineHero } from "@/components/landing/SplineHero";
import RotatingGradientRight from "@/components/ui/rotating-gradient-right";
import { Interactive3DCard } from "@/components/landing/Interactive3DCard";
import { LobeFooter } from "@/components/landing/LobeFooter";
import { IntroSpline } from "@/components/landing/IntroSpline";
import { Brain, Zap, Globe, MessageSquare } from "lucide-react";
import { motion } from "framer-motion";
import { FullScreenMenu } from "@/components/ui/FullScreenMenu";
import { LobeHeader } from "@/components/landing/LobeHeader";
import ScrollExpandMedia from "@/components/ui/scroll-expansion-hero";
import BentoGrid from "@/components/ui/bento-grid-01";
import { getBunnyStorageUrl } from "@/lib/utils/cdn-optimizer";

import Lenis from "lenis";

export default function Landing() {
    const [assetsLoaded, setAssetsLoaded] = useState(false);

    // Enforce black background and init Lenis
    useEffect(() => {
        document.body.style.backgroundColor = "#000000";

        const lenis = new Lenis();
        function raf(time: number) {
            lenis.raf(time);
            requestAnimationFrame(raf);
        }
        requestAnimationFrame(raf);

        return () => {
            document.body.style.backgroundColor = "";
            lenis.destroy();
        };
    }, []);

    return (
        <div className="min-h-screen bg-black text-white relative font-sans selection:bg-purple-500/30">
            {!assetsLoaded && <IntroSpline onComplete={() => setAssetsLoaded(true)} />}

            {assetsLoaded && (
                <>
                    <FullScreenMenu />
                    <div className="fixed top-0 left-0 right-0 z-50">
                        <LobeHeader />
                    </div>

                    <main>
                        {/* Hero Section */}
                        <SplineHero />

                        {/* Scroll Expansion Hero */}
                        <ScrollExpandMedia
                            mediaType="video"
                            isHls={false}
                            mediaSrc={getBunnyStorageUrl("gate_intro.mp4")}
                            bgImageSrc="https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?q=80&w=1920&auto=format&fit=crop"
                            title="Limitless Possibilities"
                            date="The Future is Here"
                            scrollToExpand="Scroll to Expand"
                            textBlend={true}
                        >
                            <BentoGrid />
                            {/* <div className="max-w-4xl mx-auto text-center">
                                <h3 className="text-3xl font-bold mb-6 text-white">
                                    Experience the Infinite
                                </h3>
                                <p className="text-lg text-white/80">
                                    Cryonex opens the door to a universe of knowledge. Dive deep into your studies with tools designed to expand your mind and accelerate your learning.
                                </p>
                            </div> */}
                        </ScrollExpandMedia>




                        {/* Parallax Section */}
                        <RotatingGradientRight />

                        {/* Features Grid */}
                        <section className="py-32 px-6 relative z-10">
                            <div className="max-w-7xl mx-auto">
                                <motion.h2
                                    initial={{ opacity: 0, y: 20 }}
                                    whileInView={{ opacity: 1, y: 0 }}
                                    viewport={{ once: true }}
                                    className="text-4xl md:text-6xl font-bold text-center mb-20"
                                >
                                    Unleash Your Potential
                                </motion.h2>
                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                                    <Interactive3DCard
                                        title="AI-Powered Study"
                                        description="Transform any document into interactive study materials instantly. Quizzes, flashcards, and summaries generated by AI."
                                        icon={<Brain className="w-8 h-8" />}
                                    />
                                    <Interactive3DCard
                                        title="Instant Knowledge"
                                        description="Chat with your documents using advanced RAG technology. Get citations and deep insights in seconds."
                                        icon={<Zap className="w-8 h-8" />}
                                    />
                                    <Interactive3DCard
                                        title="Global Connection"
                                        description="Connect with students and creators worldwide. Share knowledge and collaborate in real-time."
                                        icon={<Globe className="w-8 h-8" />}
                                    />
                                </div>
                            </div>
                        </section>

                        {/* Footer */}
                        <LobeFooter />
                    </main>
                </>
            )}
        </div>
    );
}