import { useCallback, useEffect, useState, useRef } from "react";
import { useParams } from "react-router";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { CheckCircle2, FileText, Play, Pause, RotateCcw, Download } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import jsPDF from "jspdf";

export default function VerifyPortal() {
    const { id } = useParams<{ id: string }>();
    const payload = useQuery(api.vault.getEssayPlayback, { essayId: id as Id<"essays"> });

    const [isPlaying, setIsPlaying] = useState(false);
    const [playbackIndex, setPlaybackIndex] = useState(0);
    const [displayedContent, setDisplayedContent] = useState("");

    const timerRef = useRef<NodeJS.Timeout | null>(null);

    const applyRevision = useCallback((current: string, rev: any) => {
        if (typeof rev.contentAfter === "string") {
            return rev.contentAfter;
        }

        const index = typeof rev.index === "number" ? rev.index : current.length;
        const removedText = typeof rev.removedText === "string" ? rev.removedText : "";
        const insertedText =
            typeof rev.insertedText === "string"
                ? rev.insertedText
                : rev.actionType === "delete"
                    ? ""
                    : rev.chunk;

        return (
            current.slice(0, index) +
            insertedText +
            current.slice(index + removedText.length)
        );
    }, []);

    // Reconstruct the document over time
    const playStep = useCallback(() => {
        if (!payload || !payload.revisions) return;

        setPlaybackIndex((prev) => {
            if (prev >= payload.revisions.length) {
                setIsPlaying(false);
                return prev;
            }

            const rev = payload.revisions[prev];
            setDisplayedContent((current) => applyRevision(current, rev));

            const next = prev + 1;
            if (next >= payload.revisions.length) {
                setDisplayedContent(payload.essay.content);
                setIsPlaying(false);
            }
            return next;
        });
    }, [applyRevision, payload]);

    useEffect(() => {
        if (isPlaying) {
            // dynamic speed based on revision density, but we'll use a flat fast speed for the demo
            timerRef.current = setInterval(playStep, 50);
        } else if (timerRef.current) {
            clearInterval(timerRef.current);
        }
        return () => {
            if (timerRef.current) clearInterval(timerRef.current);
        };
    }, [isPlaying, playStep]);

    const handleReset = () => {
        setIsPlaying(false);
        setPlaybackIndex(0);
        setDisplayedContent("");
    };

    const handleGeneratePDF = () => {
        if (!payload?.essay) return;

        const doc = new jsPDF();
        const e = payload.essay;

        // Header
        doc.setFont("helvetica", "bold");
        doc.setFontSize(22);
        doc.text("Cryonex Authenticity Report", 20, 20);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.text("Cryptographically Verified Human Effort", 20, 26);

        // Meta data
        doc.setFontSize(12);
        doc.text(`Document Title: ${e.title}`, 20, 40);
        doc.text(`Total Word Count: ${e.totalWordCount}`, 20, 48);
        const minutes = Math.ceil(e.totalTimeSpentMs / 60000);
        doc.text(`Total Active Drafting Time: ${minutes} minutes`, 20, 56);
        doc.text(`Keystroke Chunks Logged: ${payload.revisions.length}`, 20, 64);

        // Content payload
        doc.setFont("helvetica", "bold");
        doc.text("Final Document Content:", 20, 80);
        doc.setFont("helvetica", "normal");

        const splitText = doc.splitTextToSize(e.content, 170);
        doc.text(splitText, 20, 90);

        // Watermark
        doc.setTextColor(150);
        doc.setFontSize(8);
        doc.text(`Generated by Cryonex Receipts Engine • Document ID: ${e._id}`, 20, 280);

        doc.save(`${e.title.replace(/\s+/g, '_')}_Verification.pdf`);
    };

    if (payload === undefined) return <div className="p-8 text-white">Loading Verification Data...</div>;
    if (payload === null) return <div className="p-8 text-red-500">Invalid link or document not found.</div>;

    const { essay, revisions } = payload;
    const progress = revisions.length > 0 ? (playbackIndex / revisions.length) * 100 : 0;
    const timeSpentMins = Math.ceil(essay.totalTimeSpentMs / 60000);

    return (
        <div className="min-h-screen bg-white text-slate-900 font-sans selection:bg-indigo-200">
            {/* Public Header */}
            <header className="flex items-center justify-between px-8 py-4 border-b border-slate-200 bg-white/80 backdrop-blur-md sticky top-0 z-50">
                <div className="flex items-center gap-3">
                    <div className="bg-indigo-600 p-2 rounded-xl text-white shadow-sm">
                        <CheckCircle2 className="w-5 h-5" />
                    </div>
                    <div>
                        <h1 className="font-bold text-lg leading-tight tracking-tight">Cryonex Authenticity Report</h1>
                        <p className="text-xs text-slate-500 font-medium">Verified Human Effort</p>
                    </div>
                </div>
                <Button onClick={handleGeneratePDF} className="bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm rounded-full">
                    <Download className="w-4 h-4 mr-2" />
                    Download Official PDF
                </Button>
            </header>

            {/* Hero Stats */}
            <section className="bg-slate-50 border-b border-slate-200 px-8 py-10">
                <div className="max-w-4xl mx-auto flex flex-col md:flex-row gap-8 items-start md:items-center justify-between">
                    <div>
                        <h2 className="text-3xl font-serif font-semibold mb-2">{essay.title}</h2>
                        <div className="flex items-center gap-4 text-sm text-slate-500 font-medium">
                            <span className="flex items-center gap-1"><FileText className="w-4 h-4" /> {essay.status.toUpperCase()}</span>
                            <span>•</span>
                            <span>ID: <code className="bg-slate-200 px-1 py-0.5 rounded text-xs select-all text-slate-700">{essay._id}</code></span>
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-4 w-full md:w-auto">
                        <div className="bg-white border border-slate-200 p-4 rounded-2xl shadow-sm text-center">
                            <div className="text-2xl font-bold tracking-tight text-indigo-600">{timeSpentMins}m</div>
                            <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Active Time</div>
                        </div>
                        <div className="bg-white border border-slate-200 p-4 rounded-2xl shadow-sm text-center">
                            <div className="text-2xl font-bold tracking-tight text-indigo-600">{revisions.length}</div>
                            <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Keystroke Logs</div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Playback Engine */}
            <main className="max-w-4xl mx-auto px-8 py-12 pb-32">
                <div className="flex items-center justify-between mb-6">
                    <h3 className="text-lg font-bold">Drafting Timelapse</h3>
                    <div className="flex items-center gap-2">
                        <Button variant="outline" size="icon" onClick={handleReset} disabled={isPlaying || playbackIndex === 0} className="rounded-full">
                            <RotateCcw className="w-4 h-4" />
                        </Button>
                        <Button
                            variant={isPlaying ? "destructive" : "default"}
                            className={isPlaying ? "rounded-full" : "rounded-full bg-indigo-600 hover:bg-indigo-700"}
                            onClick={() => setIsPlaying(!isPlaying)}
                        >
                            {isPlaying ? <Pause className="w-4 h-4 mr-2" /> : <Play className="w-4 h-4 mr-2" />}
                            {isPlaying ? "Pause" : playbackIndex === 0 ? "Play Typing History" : "Resume"}
                        </Button>
                    </div>
                </div>

                {/* Progress Bar */}
                <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden mb-8">
                    <motion.div
                        className="h-full bg-indigo-500"
                        initial={{ width: 0 }}
                        animate={{ width: `${progress}%` }}
                        transition={{ duration: 0.1 }}
                    />
                </div>

                {/* Typed Content View */}
                <div className="bg-white border border-slate-200 shadow-sm rounded-3xl p-8 md:p-12 min-h-[500px]">
                    <AnimatePresence>
                        <motion.div
                            key="content"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            className="text-lg leading-relaxed font-serif text-slate-800 whitespace-pre-wrap"
                        >
                            {displayedContent || <span className="text-slate-300 italic">Hit play to watch the document being drafted in real-time...</span>}
                            {isPlaying && <span className="inline-block w-2 h-5 bg-indigo-500 ml-1 animate-pulse align-middle" />}
                        </motion.div>
                    </AnimatePresence>
                </div>

                {playbackIndex >= revisions.length && revisions.length > 0 && (
                    <div className="mt-8 p-4 bg-emerald-50 text-emerald-800 border border-emerald-200 rounded-2xl flex items-center justify-center gap-2 font-medium">
                        <CheckCircle2 className="w-5 h-5" /> This playback verifies the nonlinear, human creation of this document.
                    </div>
                )}
            </main>
        </div>
    );
}
